[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3fab0e91a65ce2fc513bc7f74ae1f3b5e08deef"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "36e2f3438781b480d55e8c355acd91fb826efb1b2dbef62f1147732a893895d0"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.3+0/HelFEM.v0.0.3.aarch64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e3335dd8e2e8bc886849166ecdbadc455768df3"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "b5304c55fb1dfe9dff6bec53a6ce350b404c0eae37418585ef3e7cc580e734a6"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.3+0/HelFEM.v0.0.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e0ac4e76706c1e526bcb57ab46d2d6239af99850"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "0535c5d6882d1ff6ab25a4908f09406f8ff73dbc6eaeae88c989416000d4249e"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.3+0/HelFEM.v0.0.3.i686-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e49a1582e45f9cd2eb8dafb2ba1daecc463083a"
os = "windows"

    [[HelFEM.download]]
    sha256 = "70ee9dbd2d3b3810e12b26025585fc87a5f827676a3235618e0d03b537ba8573"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.3+0/HelFEM.v0.0.3.i686-w64-mingw32-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "6197f68d1fe90289859d0d06d508d238feca738e"
os = "macos"

    [[HelFEM.download]]
    sha256 = "e41de93386d628ec7ee038b42cab1c1a82297aded8be97848e57ee83ee43f15e"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.3+0/HelFEM.v0.0.3.x86_64-apple-darwin.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eae97afc7846314a546177a833978f42ec3fabe"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "b9f63a389f098f10cf0e3e01a38cef692c04bbe5a00876cea433a2c8517bf1b2"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.3+0/HelFEM.v0.0.3.x86_64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "0a0daf60c89222974721241f363e860cbe66e9c5"
os = "freebsd"

    [[HelFEM.download]]
    sha256 = "fc28a3bb8e92aff02916f940504a9f24a16f0aaaa29b77e168d8412fc7a81a46"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.3+0/HelFEM.v0.0.3.x86_64-unknown-freebsd.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86c55b08f69e00d515e491cda787eb075830ae93"
os = "windows"

    [[HelFEM.download]]
    sha256 = "7b93f224c63789ac194acbcb6cc64d5dbf25d795aafb5ca9fe4a77c45b1347ea"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.3+0/HelFEM.v0.0.3.x86_64-w64-mingw32-cxx11.tar.gz"
