[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5575af02e136576362911bd11d01ad7445fc828"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "f1c301d9a103c9f8f1cac6a5cd2228a22760615347b19b2996303a735a4139d3"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.aarch64-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de84e5e14bd074024b4ce58f2190fc2ccc01a243"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "210030b0cd60765f08a8031f9f27be30b5fa9c6c79f667f27205936bb3cf5382"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.aarch64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9a7de5bc1fc8bb680071e534c96ebbc613f71a4"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "ea43b4454764646cbae6a6825fd0c6fdf83c4c3d0ef72621860fd6c834a40a05"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.aarch64-linux-musl-cxx03.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e7d6c9e8cfa2f178425b842b153ea36a9fadb9f"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "54ce97ed53e2de403121f9956e6519763f4d27152b396dccb011573f42fac0a6"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.aarch64-linux-musl-cxx11.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aa7a938063fec857723b020d9ecc631783ba601e"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "9530b73c0fefb234fc4898a1b231410ecf7b0dc1801d22278b483ab15e565bfd"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20234b499ed6e32e7f5b982f151178e0caa5449d"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "b03e7925e37c4339ac04997ac31561f8cffbbf09b06dec1958c68b180d2eddde"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ac354a9d7a5318a76085c6d34730730a5e3c0c2"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "4f91fef632f5c1f59a0eacc004fa0e7f043edad9b80f0ba16d6601617c2929ee"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8abda129d05c14055d0cfbb3564eced21cc2613d"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "f4f7f3e62aef0fc9c810a916832e9f0b0422d9ca1e54b72732a78096541465a9"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c1ee66625400578f7611cf9568498f091dfa805"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "4e11491813b17e808d4f36c94dd35046642649f5fab6d5d239a478cd1f97c1f0"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.i686-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "876aec4649c454199dde48e1a3d36fd9d8d3ff41"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "b7baa24da7a7159a1d3754b61eef5aee690b284146b818d9c7a6b20cd7dae4c0"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.i686-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdb78ce9d6374297f7f21b9cbb904e3d189ca77a"
os = "windows"

    [[HelFEM.download]]
    sha256 = "ce30563aff501bd4cb955c0ba9940a87f4e4c3f822bcc1df3d984dfc7965800f"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.i686-w64-mingw32-cxx03.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee428655c571235569aaef0a859a645b6cb65282"
os = "windows"

    [[HelFEM.download]]
    sha256 = "86b89446a21278604cd6fc37f0fd4c62e13dfcc56d5e5e92d4871383c77c5faf"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.i686-w64-mingw32-cxx11.tar.gz"
[[HelFEM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ddd0a8b8a6307f391d565bf66c94a640b5a0e69"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "21d71b0d3b7d3b82710188d131ec0fd053650e6a4809b833f8c9a7944259a917"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01de93b311f945aebd7360b99ae8c04a08ed4168"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "e0c60da6d4652f7f186ca7c15779410619fc44bfed4a3da32da290f1c11fda0f"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "933206e1bf5305ba6eef764741e70302aa17eca0"
os = "macos"

    [[HelFEM.download]]
    sha256 = "54158c0cc0bae5c4e10e72e5d135c7e384f8e0900edc737939602397767c10c8"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-apple-darwin.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90b7a69003d17fa6bbb24f459a8d4cd1c746b28e"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "348c7b4bada70f0d9e627cba43f63f447f11f23beab36df8b9cdfae901664030"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e94bdc7e9148416e8c60d6f048374a0925ddd3fb"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "a818c77f03742aafa21d5594cfebd46a76767333a5e91f2169701bf1fb86df7f"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "786c0aec3679c8d2bb01b5ffc1f48a50bdcff127"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "91b5d6db67642442da5d73ec94378ac28806fe26301cf07a6342bc79c2fd2114"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-linux-musl-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba699848c862055322dd8685741885ceb53f4904"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "ea65e1b228708bfb61e8d5a3ce06263d0e84881cd1799941a53a8e12835ca989"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-linux-musl-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "37cc07ebe8fb1cdb917d5dad6edff48aa4d399f5"
os = "freebsd"

    [[HelFEM.download]]
    sha256 = "34a812bc9411c357a71c448e51d540e7d1d0b8a3d340cd56ab7e8fb7d8a71699"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-unknown-freebsd.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5436233da555af200d9815551c64fd4d12ed2cc2"
os = "windows"

    [[HelFEM.download]]
    sha256 = "5075c66640d513fc43620c662f166a34a8c972ce82e7028fa1ec46ba65c97dca"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1e88f6d9707a1f69ec3b5790addde835b53e83f"
os = "windows"

    [[HelFEM.download]]
    sha256 = "40ba4dc57107a03f6e4d00a4c1506219b73a70f9aec8058ce4c9384eef58ae6e"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-w64-mingw32-cxx11.tar.gz"
