[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98d65aed031dbd97d5954a6a34986c32cf68f5e9"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "64f2e6f33ba734c6269e18fb817b1a07f62e21ff9a35b2f867ae2194c14534fa"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.aarch64-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e8a55da28c40ec049fc284dd6a066ed2b291218"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "f37c794a339a78f1945ff1f75bef13ce0c7656430bdb9b01b9aaae816ebd2f04"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.aarch64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ec32841335b331beacfcbafa5edb986912a56a9"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "1f913eac5a3c67efffc47f5fe5c0a56a79434807e94ec55ce275ea146b66af19"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.aarch64-linux-musl-cxx03.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9244f7bdc680a5e19e0c7d99d85506e89238d833"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "87f63fc34aed1e232dbc453c590e2a6a4420dd6df850e339c6f44e636182719a"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.aarch64-linux-musl-cxx11.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "656126b2959d0ac150a4549c2b7bc0cca5c69d44"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "abc3fbf1ef7b1da00b4ff0e1974393e51cf4ff3941f6b1c5d811f78d894e7828"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09bfe2dc2eb381fb944c0b536aa5fa50d3fb68e7"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "1971fe2ba5018b1c86c5dd4c71ea95fbabe16a7ee046dbe646ae4c35f3bde2b3"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99492a43de6b3c2a11d04924db614dd1ffc0ed0d"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "44babd8d339188b899937abab7aa1843536732b0404222bf5ba1654e018f2f68"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d88a51435d6a703a2c9b7564f53bb390aa788b0"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "486e515ba53cb0fd9cbd9359828c5e37355b3f338d3dceca7e3ca35663f23544"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8757d43544f6bd786cefbc641f4aa457fb84cdab"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "366867d04b8879ab6515252b0ac133a75b600642e2d2da1a24b4873089f0af83"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.i686-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65df24511406bb0789e090ba979fcdf608a67dbc"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "8779ea864568464772906daa04ce29cfd69900d044a3ae5559255408783053dd"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.i686-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "481fb4d130753da2b1625a7e8467450480737547"
os = "windows"

    [[HelFEM.download]]
    sha256 = "444f65cffb7e72ae1be67e06ed184064104d43ee90b2bcf0ffdc4f4258e29dbb"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.i686-w64-mingw32-cxx03.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e3202c1ec58f4091e312d646c5019b8af51a302"
os = "windows"

    [[HelFEM.download]]
    sha256 = "1c1f7b80445743fd48a3cfddcd5e703e18777fd89fb98ff9e0307b5598054925"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.i686-w64-mingw32-cxx11.tar.gz"
[[HelFEM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60119bda47eccaed8493d5e4a5070aa4b72b7f78"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "31a7a85b2a6c77a5c1593bf4f1ebadaea2b81a688b300449e3522390f1213004"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd57acafc63f539bc75346e1185d2a241ebc507c"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "504a0450155f7951bbb9c1c9614ac5a329fad453401f9aae99f8b41f0a45427a"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "a70899b699e571e0677a90f059873d4f7ee641ae"
os = "macos"

    [[HelFEM.download]]
    sha256 = "5e005817d4f8c65cbfc8bc6ca359305a68ecde6a29fa10ec305d4b3ae6d81500"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.x86_64-apple-darwin.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ccde143dbda1cdeb15a7bd9a6f6a480a96e50ba"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "d96fdb9f23a3d82434a58c5d83af84814c086418bcc78acae742f130c9fed167"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.x86_64-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eac4b8b1da7fff248f2e27f1425967389307234a"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "779eb3d29c855771c0c0d51e18ac734e7bbdd4103f86d74c96141fd4e0a485f5"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.x86_64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be3c31b551bf95076429541649ae146a74e5534a"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "a164ee2d8bd4bb6b175ec1b05cc994e23273adfc15489b5fbc76030ed4662f84"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.x86_64-linux-musl-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2020722626bd31ce6d2ff2f8239988b17761a765"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "567023ad170448a8e00ed78d9edcd78173ca5019496bb4a91a37bb2b0788d008"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.x86_64-linux-musl-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "70aa795a719f6c67d82190aa80403f7096b93173"
os = "freebsd"

    [[HelFEM.download]]
    sha256 = "33b309e537a2e2cd128ee02d3f03a4824d8a5373c2095110214c48e4ac2d7455"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.x86_64-unknown-freebsd.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cd1d5599597d5c7e3274571ac3d97d841090caa"
os = "windows"

    [[HelFEM.download]]
    sha256 = "6f2d3e2821be177d2e2de4e5abb703381fc7da9070e8e6e4fcd1bd6b61e5bc8c"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "649281590b2ecd05bfb628133c028026bdcda6e8"
os = "windows"

    [[HelFEM.download]]
    sha256 = "f2be9e108989887d16e673c48d53a04bad913dbbe883a74c900fcacbb304f038"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.6+0/HelFEM.v0.1.6.x86_64-w64-mingw32-cxx11.tar.gz"
