[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f758d9129e245c19382b9a990a23907d630295e"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "08f01913f6be9838d8848a647f486c6bd28560fb54824a25a62e4262dd15e7b1"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.2+0/HelFEM.v0.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a8b2e56fcab4fd50c6be2cc74806da8575a1b55"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "1e1616fd005087db990aadacc93de724d43f19d9f9ac920e0121bc46f755d2cb"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.2+0/HelFEM.v0.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2535c9cb21e4c0e0a6ae1723f72e346931f8b563"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "97644e444b08cc20ea9b9b88f0b823c36f2edb1e33242ea0ac78f7966be789d2"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.2+0/HelFEM.v0.0.2.i686-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18b803de0f777939a38074685ed6bfc5801ea11a"
os = "windows"

    [[HelFEM.download]]
    sha256 = "c3af3181f0bc153acafe79262974b2ff3e41ba0f2d6955ff18a325e3cc3ec189"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.2+0/HelFEM.v0.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "0f580e74ca143eb6ec740444bc5d7fb86cf1ee11"
os = "macos"

    [[HelFEM.download]]
    sha256 = "e9c84ee51b9c94e1e1fb204c1cb8fda8d93f2793f77b3881f5cae5e2b7c359c3"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.2+0/HelFEM.v0.0.2.x86_64-apple-darwin.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bb26e394145aed4b6b194451852bdd5c72d3e4e"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "7c7aa0a83c37bebddd9d1761c183d72aafabbd0b85217673c3f35f44676d4e70"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.2+0/HelFEM.v0.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "ad8df1347792b5d1faac933ec18e8953fd20eeae"
os = "freebsd"

    [[HelFEM.download]]
    sha256 = "de91353d6aadcc1ac2b9a0e1dfe99e7bf1d8825206656155164350172b16a167"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.2+0/HelFEM.v0.0.2.x86_64-unknown-freebsd.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcd76c48fffac5c2deee8378437578a743872c0d"
os = "windows"

    [[HelFEM.download]]
    sha256 = "106f899e1a5e07ceed045d68408afc9f3727fb76efc0ae7ae4923205a96a6875"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.0.2+0/HelFEM.v0.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
