[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0e82fac61d0da7df2c47db3fda0db5bffcaba1d"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "087445cf4fe49e67bc07a393c2389b2a5080c1ce4a55a099c878603ed46a331c"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.aarch64-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a437bb0557cd47a887f9a894618e4bd0d47d27f"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "47050f1d614450c1935d5cb9d7f1ca31f9924a6d6b0b1df1e0daba50773c2b41"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.aarch64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9388ffc86dea11239aa5a13c9f40b88e61e87c9"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "a91bedb5c45ca8989f84de4327606263efc198d1e23c8bc5d7d4b56434bc3c31"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.aarch64-linux-musl-cxx03.tar.gz"
[[HelFEM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b5d558dbb4724f9cf4b8cc51e937be3848da84a"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "4cceeea1cfd99b0a099781945f5a845a037297098fb62ac2da4408158ab8224b"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.aarch64-linux-musl-cxx11.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28512633ee810078a26017728ad7eedc90dce3f5"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "2e4b4b461b8c95ca80275e067db3ed021255870258b936fc5241179415a6f7fe"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6206c74061fece6b9b21407fd71e6223f331191c"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "28c30a5467ac75ef372548863acdc49b999992218ba31dcb2c26f49be5c3d02c"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df1a221cafd7f4d5ba37a43d770056231797fb99"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "0e443937901e30ffcab77f7f2f6e5051c3ec8f37b99920da5ec4970b2d029a14"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HelFEM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc54935359943c807cc0176f09d9f1f84bba01b6"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "8f2fbd1301c84909ebf486edf000f60fbb681da27d3f2d1ffd212940f1d9659f"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd0d6d47fe83e9c7ba46e84ee6f1f00fcaaabef5"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "19e766e5dc0c97b3f4317385129a06f7ef96adfbf35334f833b549b7fe1546b5"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.i686-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8d1b868f5b92c7b157f8d728328e220134b100a"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "6d3d9b8014f19532313f9982bdff7cb6a07ea76aa10926c9644587f5f9a944b9"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.i686-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11ee218b872a4871b0ab985e4903d7a6420adf13"
os = "windows"

    [[HelFEM.download]]
    sha256 = "5729d9df7bba1e0722621006e6d0b297504326e8b5ae56c6196a507e8749b5e2"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.i686-w64-mingw32-cxx03.tar.gz"
[[HelFEM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c753752988cccc013541dfedb1d071f37c4d963e"
os = "windows"

    [[HelFEM.download]]
    sha256 = "42af227f691d60fc3b3c4eaf37268a92d01b673f89683797a2838b9195f41525"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.i686-w64-mingw32-cxx11.tar.gz"
[[HelFEM]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d29398d2c16ca6e46d83941a6d518a6a8d4f3a04"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "d2c03f00b2a6779a0bfb98e9916d0eaba2d26bfd038fb486a8ba0520d60562be"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f5bacde4d610c786680c5351b1a49eab5e81a2e"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "1b29c1be25226efeee2b8b9efbba69c949ec24a6077bf2db1a83c281c9e048e2"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "fa48e5df30c5e7fe92f8e18358d60e86c33eba41"
os = "macos"

    [[HelFEM.download]]
    sha256 = "2b76a75676f70d5ed94a59addb38bec0553f8aec0bae5fc4f650660748a2eb73"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-apple-darwin.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d497aa0a848e25947e624661e01ed81334dcb6e8"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "32c5f2805b97ded5676b08545037affe8cc9454c8d7bcef7dfeb4c10e596f58d"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-linux-gnu-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af214593a88349b57879167fad0fd6f475a4970f"
libc = "glibc"
os = "linux"

    [[HelFEM.download]]
    sha256 = "1b6ddfd1de0978de24bc2fe17382445519e172250653c3758949d899fa6ecec8"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-linux-gnu-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88f880a63ef1bcfd9455040f136551df3145a1c4"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "7b052d6540b7af5eeca5f865f6fe41fc39ff5ed04370045362210651c9c30e79"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-linux-musl-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cacebbeb486013d38dbba975aa5815733759da54"
libc = "musl"
os = "linux"

    [[HelFEM.download]]
    sha256 = "e94012d7c44b1f46ab4fce5ef87e02c080251825fcc7aedbe3344a939c5b5523"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-linux-musl-cxx11.tar.gz"
[[HelFEM]]
arch = "x86_64"
git-tree-sha1 = "59564e9151fa879673f7dc5403091bd952450072"
os = "freebsd"

    [[HelFEM.download]]
    sha256 = "fcb19d71ef56a95bdc06370d6682ff68e0f9a74bda45f55ccc8cfb6286413d37"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-unknown-freebsd.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c069045f226ee8def8147a6ead80c435b58fcb96"
os = "windows"

    [[HelFEM.download]]
    sha256 = "af3e3d8bf287f478aab43193ac210fceeda47bbceff68f314c46892b090f70ef"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[HelFEM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5bd44e8cab67ccb819c2064d7bcdac161f10a31d"
os = "windows"

    [[HelFEM.download]]
    sha256 = "39fdd003160cdb60ce8e7571fde191ee6f18a90a3be2914aab17400eeed1f46e"
    url = "https://github.com/JuliaBinaryWrappers/HelFEM_jll.jl/releases/download/HelFEM-v0.1.5+0/HelFEM.v0.1.5.x86_64-w64-mingw32-cxx11.tar.gz"
